# github.com/example/gitops-repo/cluster-autoscaler.yaml 
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cluster-autoscaler
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster-autoscaler
      version: "9.28.0"
      sourceRef:
        kind: HelmRepository
        name: autoscaler
      interval: 15m
  values:
    autoDiscovery:
      clusterName: example-cluster
      tags:
        - k8s.io/cluster-autoscaler/enabled
        - k8s.io/cluster-autoscaler/example-cluster
    extraArgs:
      scale-down-utilization-threshold: 0.001
      scale-down-delay-after-add: 10m
      ignore-daemonsets-utilization: "true"
    rbac:
      serviceAccount:
        create: false
        name: "cluster-autoscaler"
